apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-tools

bases:
  - ../../../base/01-common-environment-config/01-quotas-and-limits/03-large
  - ../../../base/01-common-environment-config/02-rbac-argocd

resources:
  - namespace.yaml
