apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd-instance.yaml
  - developer-argocd-rolebinding.yaml
  - developer-argocd-cluster-admin.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cluster-argocd-application-controller-admin
    path: developer-argocd-rolebinding-patch.yaml