apiVersion: v1
kind: ResourceQuota
metadata:
  name: large-cpu-memory-quota
spec:
  hard:
    requests.cpu: '2'
    requests.memory: 4Gi
    limits.cpu: '6'
    limits.memory: 6Gi
  scopes:
    - NotTerminating