apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-dev

bases:
  - ../../../base/01-environments/01-resourcequota
  - ../../../base/01-environments/02-cicd-rbac

resources:
  - namespace.yaml
