apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-argocd-extended-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
      - resourcequotas
      - limitranges
    verbs:
      - '*'