kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: petclinic-dev
spec:
  destination:
    namespace: petclinic-dev
    server: https://kubernetes.default.svc
  project: petclinic
  source:
    path: overlays/petclinic/dev
    repoURL: https://github.com/pittar-demos/gitops-and-tekton-with-openshift.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true