apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/rollout-restart/base?ref=main
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/maven/base?ref=main
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/s2i-binary-build/base?ref=main

resources:
  - 01-workspace-pvc.yaml
  - 02-build-and-rollout-pipeline.yaml
  - 03-eventlistener.yaml
  - 04-trigger-route.yaml
  - 05-trigger.yaml
  - 06-trigger-binding.yaml
  - 07-trigger-template.yaml
